---
title: "十二年國教新課綱變革認同問卷之群集分析"
author: "Qi-Wen Ding"
output:
  html_notebook: default
  word_document:
always_allow_html: yes
---

# Import data

```{r, message=FALSE}
require(haven)
require(dplyr)
require(psych)
df_original = read_sav("1.2變革認同問卷TW-有效問卷-無漏答-共同樣本_final.sav")
df = select(df_original, one_of("ID","sys","group","gender","edu","q1to8Mean","q9to16Mean_D12","q17to32Mean_D17_24_25","q33to40Mean",
                           "q70Ato76AMean", "q70Bto76BMean","q2to4Mean","q5to8Mean","q9to11Mean","q13to16Mean","q18to20Mean",
                           "q21to23Mean","q26to28Mean","q29to32Mean","q33to36Mean","q37to40Mean"))
df$ID = factor(df$ID); df$gender = factor(df$gender); df$group = factor(df$group)
# Remove the first item in the first dimension
df$q1to8Mean = (df_original$q2 + df_original$q3 + df_original$q4 + df_original$q5 + df_original$q6 + df_original$q7 + df_original$q8)/7
colnames(df)[6] = "q1to8Mean_D1"
```

# Profile of each participants (after within-person standardization)

  * 6 dimensions parallel coordinates plot 


```{r}
require(reshape2)
require(GGally)
# Standardization by row
rowScale = function(x, center = TRUE, scale = TRUE, add_attr = TRUE, rows = NULL, cols = NULL) {
    library(matrixStats)
  
    if (!is.null(rows) && !is.null(cols)) {
        x <- x[rows, cols, drop = FALSE]
    } else if (!is.null(rows)) {
        x <- x[rows, , drop = FALSE]
    } else if (!is.null(cols)) {
        x <- x[, cols, drop = FALSE]
    }
 
  # Get the column means
    cm = rowMeans(x, na.rm = TRUE)
  # Get the column sd
    if (scale) {
        csd = rowSds(x, center = cm)
    } else {
        # just divide by 1 if not
        csd = rep(1, length = length(cm))
    }
    if (!center) {
        # just subtract 0
        cm = rep(0, length = length(cm))
    }
    x = (x - cm) / csd
    if (add_attr) {
        if (center) {
            attr(x, "scaled:center") <- cm
        }
        if (scale) {
            attr(x, "scaled:scale") <- csd
        }
    }
    return(x)
}

df_6dim = df[,1:11]
df_6dim[,6:ncol(df_6dim)] = rowScale(df_6dim[,6:ncol(df_6dim)], center = T, scale = T, add_attr = F) # Within-person standardization
df_6dim[which(df_6dim$q1to8Mean_D1 == "NaN"), 6:ncol(df_6dim)] = 0 # Replace score with no variation by 0

colnames(df_6dim) = c("ID", "學制", "國中或高中樣本", "性別", "最高學歷", "領導觀", "課程觀", "教學觀", "評鑑觀", "變革喜好", "變革願意實踐")



df_6dim_l = melt(df_6dim,
                  id.vars = c("ID", "學制", "國中或高中樣本", "性別", "最高學歷"),
                  measure.vars = colnames(df_6dim)[6:11],
                  variable.name="Dimension",
                  value.name="Score"
                 )

ggparcoord(df_6dim, columns=6:11, groupColumn = 3, alphaLines = 0.3,
           title = "6 dimensions parallel coordinates plot")
```


# Hierarchical clustering (Ward's method with squared Euclidean distance)

```{r, dev = 'win.metafile'}
# Check scatter plot first
pairs.panels(df_6dim[,6:11])

# Hierarchical clustering
E.dist2 = dist(df_6dim[,6:11], method = "euclidean")^2

# 3 or 4 clusters suggested
h.E.w.cluster = hclust(E.dist2, method = "ward.D2")
plot(h.E.w.cluster, hang = -1, labels = F, xlab = "Wald's method") 
abline(h = 21.5, lty = 2, col = "red")

require(factoextra)
tree.W6dimstd = fviz_dend(h.E.w.cluster, show_labels = F,#cex = 0.5,
                   k = 3, k_colors = c("#00AFBB", "#E7B800", "#FC4E07"), # "darkorchid"
                   color_labels_by_k = T,
                   rect = T) + 
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12)
  )
saveRDS(tree.W6dimstd, file = "tree.W6dimstd.RDS")
```



# Non-hierarchical *k*-means clustering
  
```{r, dev = 'win.metafile'}
require(factoextra)
set.seed(20190903)
# Determine number of clusters
fviz_nbclust(df_6dim[,6:ncol(df_6dim)], 
             FUNcluster = kmeans,
             method = "wss",     # total within cluster sum of square
             k.max = 7          # max number of clusters to consider
             ) +
  labs(title="Elbow method for K-means") +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12)
  )

# K-means cluster
set.seed(20190903)
kmeans.cluster4 = kmeans(df_6dim[,6:ncol(df_6dim)], centers = 4, nstart = 100)
kmeans.cluster3 = kmeans(df_6dim[,6:ncol(df_6dim)], centers = 3, nstart = 100)

# Visualize the clusters
PCA.4grp = fviz_cluster(kmeans.cluster4,  
             data = df_6dim[,6:ncol(df_6dim)],             
             geom = c("point"), #c("point","text") shows both point & label
             ellipse.type = "norm",
             star.plot = T # Add segments from centroids to items
             ) +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank()
  ) 

PCA.3grp = fviz_cluster(kmeans.cluster3,  
             data = df_6dim[,6:ncol(df_6dim)],             
             geom = c("point"), #c("point","text") shows both point & label
             ellipse.type = "norm",
             star.plot = T # Add segments from centroids to items
             ) +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank()
  ) 
```



# Cluster profile
  
```{r, dev = 'win.metafile'}
# Sample size in each cluster
kmeans.cluster3$size
kmeans.cluster4$size

# Mean profile
#kmeans.cluster3$centers
#kmeans.cluster4$centers

# Combine the cluster group info into the original data frame
df_6dim$Cluster_3grp = factor(kmeans.cluster3$cluster)
df_6dim$Cluster_4grp = factor(kmeans.cluster4$cluster)

stat.3gp = describeBy(df_6dim, group = df_6dim$Cluster_3grp, digits = 4) # The info here is identicial to the mean profile
stat.4gp = describeBy(df_6dim, group = df_6dim$Cluster_4grp, digits = 4)


dfwithMSD = function(stat.list){
  require(dplyr)
  df.list = list()
  for (i in 1:length(stat.list)){
    df.list[[i]] = data.frame(stat.list[[i]][6:11, 3:4])
    df.list[[i]]$Dimension = rownames(df.list[[i]])
    df.list[[i]]$Cluster = i
  }
  df = bind_rows(df.list)
  df$Dimension = factor(df$Dimension); df$Cluster = factor(df$Cluster)
  return(df)
}
stat.3gp.df = dfwithMSD(stat.3gp)
stat.4gp.df = dfwithMSD(stat.4gp)


CAprofile = function(df){
  ggplot(df, aes(x = Dimension, y = mean,
                                      group = Cluster, color = Cluster, shape = Cluster)) +
  geom_line(size=1) +
  geom_point(size=3) +
  geom_errorbar(aes(x = Dimension, ymin = mean-sd, ymax = mean+sd),
                width=.3, position=position_dodge(width = .1)) +
  labs(x = '量表子向度',
       y = '平均得分',
       title = 'Mean profile of each cluster',
       caption = "誤差線為平均數 ± 一個標準差") +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12)
  ) 
}

profile.3gp = CAprofile(stat.3gp.df) + scale_x_discrete(limits=c("領導觀", "課程觀", "教學觀", "評鑑觀", "變革喜好", "變革願意實踐"))
profile.4gp = CAprofile(stat.4gp.df)  + scale_x_discrete(limits=c("領導觀", "課程觀", "教學觀", "評鑑觀", "變革喜好", "變革願意實踐"))

# Cluster scatter plot
colorlow <- hcl.colors(3, alpha = .5)[kmeans.cluster3$cluster]
pairs(df_6dim[,6:11], pch = 16, gap = 0, col = colorlow, oma=c(3,3,3,16))
par(xpd = T) # allow plotting of the legend outside the figure region  (ie within the space left by making the margins big)
legend(0.75, 0.675, legend = 1:3,  fill = hcl.colors(3), bty = "n", title = "Cluster")


colorlow <- hcl.colors(4, alpha = .5)[kmeans.cluster4$cluster]
pairs(df_6dim[,6:11], pch = 16, gap = 0, col = colorlow, oma=c(3,3,3,16))
par(xpd = T) # allow plotting of the legend outside the figure region  (ie within the space left by making the margins big)
legend(0.75, 0.675, legend = 1:4,  fill = hcl.colors(4), bty = "n", title = "Cluster")
```


# Subgroup analysis

  * `group` = 0 (國中樣本)
 
```{r, dev = 'win.metafile'}
df_6dim_j = subset(df_6dim, `國中或高中樣本` == 0)

E.dist.6j2 = dist(df_6dim_j[,6:11], method = "euclidean")^2

set.seed(20190903)
h.E.w.cluster.6j = hclust(E.dist.6j2, method = "ward.D2")

tree.6jstd = fviz_dend(h.E.w.cluster.6j, show_labels = F,#cex = 0.5,
                   k = 3, k_colors = c("#00AFBB", "#E7B800", "#FC4E07"), #"darkorchid"
                   color_labels_by_k = T,
                   rect = T) + 
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12)
  )
saveRDS(tree.6jstd, file = "tree.6jstd.RDS")


fviz_nbclust(df_6dim_j[,6:11],
             FUNcluster = kmeans,
             method = "wss",     # total within cluster sum of square
             k.max = 7         # max number of clusters to consider
             ) +
  labs(title="Elbow method for K-means") +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12)
  )


# K-means cluster
set.seed(20190903)
kmeans.cluster3.6j = kmeans(df_6dim_j[,6:11], centers = 3, nstart = 100)

# Visualize the clusters
PCA.3grp.6j = fviz_cluster(kmeans.cluster3.6j,  
             data = df_6dim_j[,6:11],             
             geom = c("point"), #c("point","text") shows both point & label
             ellipse.type = "norm",
             star.plot = T # Add segments from centroids to items
             ) +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank()
  ) 


# Sample size in each cluster
kmeans.cluster3.6j$size

# Combine the cluster group info into the original data frame
df_6dim_j$Cluster_3grp = factor(kmeans.cluster3.6j$cluster)

stat.3gp.6j = describeBy(df_6dim_j, group = df_6dim_j$Cluster_3grp, digits = 4) 
stat.3gp.df.6j = dfwithMSD(stat.3gp.6j)


profile.3gp.6j = CAprofile(stat.3gp.df.6j) + scale_x_discrete(limits=c("領導觀", "課程觀", "教學觀", "評鑑觀", "變革喜好", "變革願意實踐"))

# Cluster scatter plot
colorlow <- hcl.colors(3, alpha = .5)[kmeans.cluster3.6j$cluster]
pairs(df_6dim_j[,6:11], pch = 16, gap = 0, col = colorlow, oma=c(3,3,3,15))
par(xpd = T) # allow plotting of the legend outside the figure region  (ie within the space left by making the margins big)
legend(0.75, 0.675, legend = 1:3,  fill = hcl.colors(3), bty = "n", title = "Cluster")
```
  
  * `group` = 1 (高中樣本)

```{r}
df_6dim_s = subset(df_6dim, `國中或高中樣本` == 1)
E.dist.6s2 = dist(df_6dim_s[,6:11], method = "euclidean")^2

set.seed(20190903)
h.E.w.cluster.6s = hclust(E.dist.6s2, method = "ward.D2")

tree.6sstd = fviz_dend(h.E.w.cluster.6s, show_labels = F,#cex = 0.5,
                   k = 3, k_colors = c("#00AFBB", "#E7B800", "#FC4E07"), #"darkorchid"
                   color_labels_by_k = T,
                   rect = T) + 
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank(),
        axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        text = element_text(size = 12)
  )
saveRDS(tree.6sstd, file = "tree6sstd.RDS")



fviz_nbclust(df_6dim_s[,6:11], # df_12dim[,6:17]
             FUNcluster = kmeans,
             method = "wss",     # total within cluster sum of square
             k.max = 7          # max number of clusters to consider
             ) +
  labs(title="Elbow method for K-means") +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank()
  )


# K-means cluster
set.seed(20190903)
kmeans.cluster3.6s = kmeans(df_6dim_s[,6:11], centers = 3, nstart = 100)

# Visualize the clusters
PCA.3grp.6s = fviz_cluster(kmeans.cluster3.6s,  
             data = df_6dim_s[,6:11],             
             geom = c("point"), #c("point","text") shows both point & label
             ellipse.type = "norm",
             star.plot = T # Add segments from centroids to items
             ) +
  theme_classic() +
  theme(legend.position = "bottom",
        rect = element_rect(fill = "transparent"),
        plot.background = element_rect(fill = "transparent", color = NA),
        panel.background = element_blank()
  ) 


# Sample size in each cluster
kmeans.cluster3.6s$size

# Combine the cluster group info into the original data frame
df_6dim_s$Cluster_3grp = factor(kmeans.cluster3.6s$cluster)

stat.3gp.6s = describeBy(df_6dim_s, group = df_6dim_s$Cluster_3grp, digits = 4) 
stat.3gp.df.6s = dfwithMSD(stat.3gp.6s)

 
profile.3gp.6s = CAprofile(stat.3gp.df.6s) + scale_x_discrete(limits=c("領導觀", "課程觀", "教學觀", "評鑑觀", "變革喜好", "變革願意實踐"))


# Cluster scatter plot
colorlow <- hcl.colors(3, alpha = .5)[kmeans.cluster3.6s$cluster]
pairs(df_6dim_s[,6:11], pch = 16, gap = 0, col = colorlow, oma=c(3,3,3,15))
par(xpd = T) # allow plotting of the legend outside the figure region  (ie within the space left by making the margins big)
legend(0.75, 0.675, legend = 1:3,  fill = hcl.colors(3), bty = "n", title = "Cluster")
```